/// FColoring
///
/// Colors each pixel based on the data generated by the FComputer.
///
/// In the process model, it is the second phase, i.e.
///
///		FComputer -> FColoring -> FOutput
///                  ^^^^^^^^^
///

public protocol FColoring {
	associatedtype ColorType
	associatedtype ZValue
	func colorAt(point: Point, value: ZValue) -> Color<ColorType>
}
